language: node_js
node_js:
- '0.11'
- '0.10'
script:
- mocha
- jshint main.js lib/ test/
- jscs main.js lib/ test/
env:
  global:
  - secure: Snil9qE37z0EVbjVI1AOIaObLnH95Iac7y3IBwTMbuMVaCIi8rHS9Gs/2DCdiZdGNt7dTsh6QeVtVIbsH/fQs3S7cEX6E8V++1P7waEQ+QngKiEvE648dsMt9aTIS6YoGo/0srSgehFEocuHj+FU3e2EbYQ3nzi3t2ZThvvNkq8=
  - secure: feD1efbA6NLZSOlIQ3bIC/nNl/piuzjrYf2agNbCmGaNHwLHAvtareOPK/bxPFyMc431aQKvrDbMjaV2VdPly0XcPg8ZsPKtxAI2xk9dwt1FF0NqFaNb4rh59+4IOoJJRjriLerWHc2MvrzZ8tPYid0HtMlfzDgbvfAAba0lBWU=
notifications:
  slack:
    secure: gybn0stlysc78PYGwAxLGKQuwilHsViQe7fQ9VZTnKw8XQ4qdWxZC7Gk3Sg6XNntCSFYT8bSAO8LDQsT0yutODJ1ErxGuMRuJElSktRr5ylerWgzXbcpDyCA+hI1tzso94ITLTOamw9tGn8FyGvhMAMkByLZYpzuMjiWn+5BbzI=
